// Realtek firmware embedded in the kext, unmodified (build/firmware_blob.c is generated by the
// Makefile with xxd from firmware/*.bin). License: firmware/LICENCE.rtlwifi_firmware.txt.
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char rtl8761bu_fw_bin[];
extern const unsigned int rtl8761bu_fw_bin_len;
extern const unsigned char rtl8761bu_config_bin[];
extern const unsigned int rtl8761bu_config_bin_len;

#ifdef __cplusplus
}
#endif
